### ISSUE TITLE
There is '?' in the melody for which there is no explanation in Hughes' book

### ISSUE THREAD

**Issue by juyaolongpaul** [DDMAL/Andrew-Hughes-Chant#12]
When I debugged the function of slur, I found out this problem. Just search for '?.' in the original file, and you will find about 27 matches. So there are some files that are messed up.

**Comment by fujinaga** [comment]
Ask Kate if she knows what the '?' means. Meanwhile, fix the code so that it ignores the '?'.

**Comment by juyaolongpaul** [comment]
OK, I will write an email to ask her soon.

**Comment by juyaolongpaul** [comment]
"?" indicates the notes Hughes was not sure about. Prof. Helsen suggests just a blank portion of staff lines above the syllable indicated, or perhaps an asterisk, etc to indicate the missing pitch.

**Comment by musicus** [comment]
A blank portion in the staff, with an asterisk above the staff (where the blank portion is located) is fine.

**Comment by juyaolongpaul** [comment]
I have iterated all the elements in `<note>`, and have not found that there is anything can be rendered as a blank portion, leaving an asterisk on the staff. The most realistic way now is to add a special note to indicate `?`. One possible way is to add an "Accent" note. I will work this way first, and if you want a better proposal, let me know so that I can modify afterward.

**Comment by ahankinson** [comment]
You should attempt to encode things semantically and not just visually. There are several options in MEI. You can look into using the `sic` and `corr` elements:

http://music-encoding.org/documentation/3.0.0/sic/
http://music-encoding.org/documentation/3.0.0/corr/

The `gap` element may also be what you're looking for:

http://music-encoding.org/documentation/3.0.0/gap/

Or `unclear`:

http://music-encoding.org/documentation/3.0.0/unclear/

Or `supplied`:

http://music-encoding.org/documentation/3.0.0/supplied/

**Comment by ahankinson** [comment]
If Verovio will not render these now, you can seek advice from the Verovio developers about how best to work with these MEI elements.

**Comment by juyaolongpaul** [comment]
Thank you for your reply. Seems like all these elements work in a semantical way, but not visual way, which means `?`will not be rendered as a note, and therefore the lyrics and notes will mismatch at this point. From Prof. Helsen's perspective, she wants the alignment between notes and lyrics, so at this point, I will add "Accent" note to indicate that, and incorporate this mapping into "README" file, and I will use `unclear` element to explain semantically in the MEI file as well. At the same time, I will raise an issue on Verovio's Github repository about this problem.

**Comment by juyaolongpaul** [comment]
The solution is in here: https://github.com/rism-ch/verovio/issues/599#issuecomment-302108779
