### ISSUE TITLE
File Naming Redundancy

### ISSUE THREAD

**Issue by musicus** [DDMAL/Andrew-Hughes-Chant#14]
```Files_Pitch``` > ```ADALARDUS``` > ```AD00``` > ```AD00=2nd_Vespers```

The second ```AD00=``` seems redundant (the previous directory ```AD00``` seems superfluous since there is only one _Adalardus_).

**Comment by juyaolongpaul** [comment]
There are some exceptions: when I remove the part you suggest, the file name will be blank, so in this case, I just name the file name as `NO_NAME`. For example: `CH-X` > `0504_XC68_Holy_Crown_of_Thorns` > `XC68_8=0504` > `NO_NAME`. Originally, it will be `XC68=`.
