### ISSUE TITLE
O_virum_nobilem.mei feast metadata

### ISSUE THREAD

**Issue by musicus** [DDMAL/Andrew-Hughes-Chant#17]
You should include the feast in the ```meiHead```.

**Comment by juyaolongpaul** [comment]
Before you decide to raise up several detailed issues from the same category, I think you should see #11, which is already addressed before. These issues are true, but from the bigger issue which is already addressed, and therefore, redundant. You should close them sometime soon. @fujinaga

**Comment by musicus** [comment]
I looked at the .mei file and the requested metadata is not contained in the ```meiHead```.
