### ISSUE TITLE
Previous .mei files

### ISSUE THREAD

**Issue by musicus** [DDMAL/Andrew-Hughes-Chant#2]
In a previous version that generated the ```.mei``` file the meta is missing. You should include Andrew Hughes' meta data within the ```<meiHead>```.

**Comment by juyaolongpaul** [comment]
Yes, and now a scheme of how to extract the meta-data is needed.

**Comment by musicus** [comment]
Please consult #11.

**Comment by musicus** [comment]
Part of #11 now.
