### ISSUE TITLE
O_virum_nobilem.mei Empty Measures in Verovio

### ISSUE THREAD

**Issue by musicus** [DDMAL/Andrew-Hughes-Chant#20]
When I render ```O_virum_nobilem.mei``` in Verovio (in 4/4 time), there appear to be several blank measures.

![o-virum-nobilem_empty-measures](https://cloud.githubusercontent.com/assets/1203470/26061970/786a66e2-3957-11e7-93f1-7ef9e493e0c3.png)

**Comment by juyaolongpaul** [comment]
Again, the file you render is not from the newest commit. In the newest commit, it looks like this:
![screen shot 2017-05-17 at 10 21 08 am](https://cloud.githubusercontent.com/assets/9313094/26158710/9422ed34-3aea-11e7-8669-121f4c3817e5.png)

I already fix the problem of blank measure error in #7.

**Comment by musicus** [comment]
Merge dev into master?

**Comment by juyaolongpaul** [comment]
Just did.
