### ISSUE TITLE
O_virum_nobilem.mei Small Notes in Verovio

### ISSUE THREAD

**Issue by musicus** [DDMAL/Andrew-Hughes-Chant#21]
When I render ```O_virum_nobilem.mei``` in Verovio (in 4/4 time), there appear to be several noteheads smaller than the other noteheads.

![o-virum-nobilem_small-notes](https://cloud.githubusercontent.com/assets/1203470/26062013/a1ac7144-3957-11e7-97b4-6b6cf02c3220.png)

**Comment by juyaolongpaul** [comment]
It is a plica, and after talking with Prof. Helsen, we decide to use grace note to indicate that.
