### ISSUE TITLE
Lyrics metadata

### ISSUE THREAD

**Issue by musicus** [DDMAL/Andrew-Hughes-Chant#23]
You should include the text in the ```meiHead```.

**Comment by juyaolongpaul** [comment]
I think the lyrics will be added to align up with the melody once #5 is solved. I wonder whether it is still necessary to incorporate lyrics as meta-data or not.

**Comment by juyaolongpaul** [comment]
@fujinaga

**Comment by juyaolongpaul** [comment]
I have consulted Prof. Helsen, it is not needed at this point, at least. Will check out with her again after #5 is finished.

**Comment by fujinaga** [comment]
I think lyrics should be included in the header so that lyrics can be easily searched across many files.

**Comment by juyaolongpaul** [comment]
Ok, I will add them soon.
