### ISSUE TITLE
Directory Names

### ISSUE THREAD

**Issue by musicus** [DDMAL/Andrew-Hughes-Chant#4]
The file paths, file names, and directory names need to be readable and not contain any special characters.

**Comment by juyaolongpaul** [comment]
The temporary results solve the problem partially, and I will work on how to deal with the exceptions in Andrew Hughe's original encodings, which is a bit hard to translate into a understandable format.

**Comment by musicus** [comment]
What's the progress on this?

**Comment by juyaolongpaul** [comment]
This is a bit complicated. I have examined the whole file system again, and I found out that the majority of them is translated completely. However, for ```CH-D-0~7```, I can not find references from the [website](http://hlub.dyndns.org/projekten/webplek/CANTUS/cgi-bin/LMLO/index.cgi?saintlist=true) you sent to me to translate properly. Please have a look at the name of the child folders under ```CH-D-0~7```.   For the rest volumes, there are one or two child folders beginning with ```<MDBO>>...``` are not translated either, and I suppose this is also about inconsistencies of the original encodings. I will further look into this during the "re-writing script" process. 

I think at this point, you can have a look at ```CH-D-0~7```, and it will be great if we can come up with a scheme to translate these names properly.

**Comment by juyaolongpaul** [comment]
Still do not have a scheme how to translate the fold names under ```CH-D-0~7```, and the references are not found [website](http://hlub.dyndns.org/projekten/webplek/CANTUS/cgi-bin/LMLO/index.cgi?saintlist=true),
