### ISSUE TITLE
Reformatting the script

### ISSUE THREAD

**Issue by juyaolongpaul** [DDMAL/Andrew-Hughes-Chant#8]
The script needs to be reformatted by PEP 8 style.

**Comment by fujinaga** [comment]
Please follow the "Other Recommendations" as well. For example: "Always surround these binary operators with a single space on either side: assignment ( = ), augmented assignment ( += , -= etc.), comparisons ( == , < , > , != , <> , <= , >= , in , not in , is , is not ), Booleans ( and , or , not )."

**Comment by juyaolongpaul** [comment]
Learn to use the inspector of Pycharm to reformat the code with PEP 8 Style.

**Comment by musicus** [comment]
Know the PEP 8 style: https://www.python.org/dev/peps/pep-0008/.

**Comment by vigliensoni** [comment]
I would suggest to use a linter plugin to conform to PEP8 within PyCharm

https://www.pylint.org/

**Comment by juyaolongpaul** [comment]
Just upload the new script. And @musicus yes, this is the official link. I have read this once and highlighted the key point, and tried to reformatted my code a bit, but it seems like to fully carry out the rules manually. So now I am using pep8 toolkit which is embedded in Pycharm by default to inspect whether the script has fully complied with PEP 8 Style or now, and I think pylint is another tool right? @vigliensoni.

**Comment by vigliensoni** [comment]
I haven't tried the PEP8 toolkit in Pycharm, but it should be fine.

**Comment by musicus** [comment]
@juyaolongpaul you do not need to fully carry out all of the rules: https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds

**Comment by juyaolongpaul** [comment]
@musicus Yes, I know what do you mean, and I also can see the possible drawback of fully implementing this style. So that's why I changed some according to PEP 8 and left out the rest. But it seems like there is not enough credit for me to justify my preference over the PEP 8 Style at this point, so I think fully carrying out this style might be a better idea, but thank you for sharing.
