### ISSUE TITLE
Some MEI files are blank

### ISSUE THREAD

**Issue by juyaolongpaul** [DDMAL/Andrew-Hughes-Chant#9]
It is found that some MEI files, such as the ones under 'CH-D-7' are blank.

**Comment by fujinaga** [comment]
This is very serious. 
Before you work on any new "features" please fix this by using a proper XML library (e.g., lxml) to generate the MEI files then "validate" the results.

**Comment by juyaolongpaul** [comment]
Bug solved, they are blank because Andrew used a different encoding scheme, which he has not explicitly talked about in his book.
